// Copyright 2019 kurosawa. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// =============================================================================
package cu

// #include "/usr/local/cuda/include/cuda.h"
import "C"

type CuDesc struct {
	context CUcontext
}

var cuDescMap = make(map[CUdevice]CuDesc)

type CUdevice C.CUdevice
type CUcontext C.CUcontext
type CUdeviceptr C.CUdeviceptr
type CUmodule C.CUmodule
type CUfunction C.CUfunction
type CUstream C.CUstream
type CUuuid C.CUuuid

type CUhostptr uintptr
type CUresult C.CUresult
type CUdevice_attribute C.CUdevice_attribute

const (
	CUDA_SUCCESS                              = C.CUDA_SUCCESS
	CUDA_ERROR_INVALID_VALUE                  = C.CUDA_ERROR_INVALID_VALUE
	CUDA_ERROR_OUT_OF_MEMORY                  = C.CUDA_ERROR_OUT_OF_MEMORY
	CUDA_ERROR_NOT_INITIALIZED                = C.CUDA_ERROR_NOT_INITIALIZED
	CUDA_ERROR_DEINITIALIZED                  = C.CUDA_ERROR_DEINITIALIZED
	CUDA_ERROR_PROFILER_DISABLED              = C.CUDA_ERROR_PROFILER_DISABLED
	CUDA_ERROR_PROFILER_NOT_INITIALIZED       = C.CUDA_ERROR_PROFILER_NOT_INITIALIZED
	CUDA_ERROR_PROFILER_ALREADY_STARTED       = C.CUDA_ERROR_PROFILER_ALREADY_STARTED
	CUDA_ERROR_PROFILER_ALREADY_STOPPED       = C.CUDA_ERROR_PROFILER_ALREADY_STOPPED
	CUDA_ERROR_NO_DEVICE                      = C.CUDA_ERROR_NO_DEVICE
	CUDA_ERROR_INVALID_DEVICE                 = C.CUDA_ERROR_INVALID_DEVICE
	CUDA_ERROR_INVALID_IMAGE                  = C.CUDA_ERROR_INVALID_IMAGE
	CUDA_ERROR_INVALID_CONTEXT                = C.CUDA_ERROR_INVALID_CONTEXT
	CUDA_ERROR_CONTEXT_ALREADY_CURRENT        = C.CUDA_ERROR_CONTEXT_ALREADY_CURRENT
	CUDA_ERROR_MAP_FAILED                     = C.CUDA_ERROR_MAP_FAILED
	CUDA_ERROR_UNMAP_FAILED                   = C.CUDA_ERROR_UNMAP_FAILED
	CUDA_ERROR_ARRAY_IS_MAPPED                = C.CUDA_ERROR_ARRAY_IS_MAPPED
	CUDA_ERROR_ALREADY_MAPPED                 = C.CUDA_ERROR_ALREADY_MAPPED
	CUDA_ERROR_NO_BINARY_FOR_GPU              = C.CUDA_ERROR_NO_BINARY_FOR_GPU
	CUDA_ERROR_ALREADY_ACQUIRED               = C.CUDA_ERROR_ALREADY_ACQUIRED
	CUDA_ERROR_NOT_MAPPED                     = C.CUDA_ERROR_NOT_MAPPED
	CUDA_ERROR_NOT_MAPPED_AS_ARRAY            = C.CUDA_ERROR_NOT_MAPPED_AS_ARRAY
	CUDA_ERROR_NOT_MAPPED_AS_POINTER          = C.CUDA_ERROR_NOT_MAPPED_AS_POINTER
	CUDA_ERROR_ECC_UNCORRECTABLE              = C.CUDA_ERROR_ECC_UNCORRECTABLE
	CUDA_ERROR_UNSUPPORTED_LIMIT              = C.CUDA_ERROR_UNSUPPORTED_LIMIT
	CUDA_ERROR_CONTEXT_ALREADY_IN_USE         = C.CUDA_ERROR_CONTEXT_ALREADY_IN_USE
	CUDA_ERROR_PEER_ACCESS_UNSUPPORTED        = C.CUDA_ERROR_PEER_ACCESS_UNSUPPORTED
	CUDA_ERROR_INVALID_PTX                    = C.CUDA_ERROR_INVALID_PTX
	CUDA_ERROR_INVALID_GRAPHICS_CONTEXT       = C.CUDA_ERROR_INVALID_GRAPHICS_CONTEXT
	CUDA_ERROR_NVLINK_UNCORRECTABLE           = C.CUDA_ERROR_NVLINK_UNCORRECTABLE
	CUDA_ERROR_JIT_COMPILER_NOT_FOUND         = C.CUDA_ERROR_JIT_COMPILER_NOT_FOUND
	CUDA_ERROR_INVALID_SOURCE                 = C.CUDA_ERROR_INVALID_SOURCE
	CUDA_ERROR_FILE_NOT_FOUND                 = C.CUDA_ERROR_FILE_NOT_FOUND
	CUDA_ERROR_SHARED_OBJECT_SYMBOL_NOT_FOUND = C.CUDA_ERROR_SHARED_OBJECT_SYMBOL_NOT_FOUND
	CUDA_ERROR_SHARED_OBJECT_INIT_FAILED      = C.CUDA_ERROR_SHARED_OBJECT_INIT_FAILED
	CUDA_ERROR_OPERATING_SYSTEM               = C.CUDA_ERROR_OPERATING_SYSTEM
	CUDA_ERROR_INVALID_HANDLE                 = C.CUDA_ERROR_INVALID_HANDLE
	CUDA_ERROR_ILLEGAL_STATE                  = C.CUDA_ERROR_ILLEGAL_STATE
	CUDA_ERROR_NOT_FOUND                      = C.CUDA_ERROR_NOT_FOUND
	CUDA_ERROR_NOT_READY                      = C.CUDA_ERROR_NOT_READY
	CUDA_ERROR_ILLEGAL_ADDRESS                = C.CUDA_ERROR_ILLEGAL_ADDRESS
	CUDA_ERROR_LAUNCH_OUT_OF_RESOURCES        = C.CUDA_ERROR_LAUNCH_OUT_OF_RESOURCES
	CUDA_ERROR_LAUNCH_TIMEOUT                 = C.CUDA_ERROR_LAUNCH_TIMEOUT
	CUDA_ERROR_LAUNCH_INCOMPATIBLE_TEXTURING  = C.CUDA_ERROR_LAUNCH_INCOMPATIBLE_TEXTURING
	CUDA_ERROR_PEER_ACCESS_ALREADY_ENABLED    = C.CUDA_ERROR_PEER_ACCESS_ALREADY_ENABLED
	CUDA_ERROR_PEER_ACCESS_NOT_ENABLED        = C.CUDA_ERROR_PEER_ACCESS_NOT_ENABLED
	CUDA_ERROR_PRIMARY_CONTEXT_ACTIVE         = C.CUDA_ERROR_PRIMARY_CONTEXT_ACTIVE
	CUDA_ERROR_CONTEXT_IS_DESTROYED           = C.CUDA_ERROR_CONTEXT_IS_DESTROYED
	CUDA_ERROR_ASSERT                         = C.CUDA_ERROR_ASSERT
	CUDA_ERROR_TOO_MANY_PEERS                 = C.CUDA_ERROR_TOO_MANY_PEERS
	CUDA_ERROR_HOST_MEMORY_ALREADY_REGISTERED = C.CUDA_ERROR_HOST_MEMORY_ALREADY_REGISTERED
	CUDA_ERROR_HOST_MEMORY_NOT_REGISTERED     = C.CUDA_ERROR_HOST_MEMORY_NOT_REGISTERED
	CUDA_ERROR_HARDWARE_STACK_ERROR           = C.CUDA_ERROR_HARDWARE_STACK_ERROR
	CUDA_ERROR_ILLEGAL_INSTRUCTION            = C.CUDA_ERROR_ILLEGAL_INSTRUCTION
	CUDA_ERROR_MISALIGNED_ADDRESS             = C.CUDA_ERROR_MISALIGNED_ADDRESS
	CUDA_ERROR_INVALID_ADDRESS_SPACE          = C.CUDA_ERROR_INVALID_ADDRESS_SPACE
	CUDA_ERROR_INVALID_PC                     = C.CUDA_ERROR_INVALID_PC
	CUDA_ERROR_LAUNCH_FAILED                  = C.CUDA_ERROR_LAUNCH_FAILED
	CUDA_ERROR_COOPERATIVE_LAUNCH_TOO_LARGE   = C.CUDA_ERROR_COOPERATIVE_LAUNCH_TOO_LARGE
	CUDA_ERROR_NOT_PERMITTED                  = C.CUDA_ERROR_NOT_PERMITTED
	CUDA_ERROR_NOT_SUPPORTED                  = C.CUDA_ERROR_NOT_SUPPORTED
	CUDA_ERROR_SYSTEM_NOT_READY               = C.CUDA_ERROR_SYSTEM_NOT_READY
	CUDA_ERROR_SYSTEM_DRIVER_MISMATCH         = C.CUDA_ERROR_SYSTEM_DRIVER_MISMATCH
	CUDA_ERROR_COMPAT_NOT_SUPPORTED_ON_DEVICE = C.CUDA_ERROR_COMPAT_NOT_SUPPORTED_ON_DEVICE
	CUDA_ERROR_STREAM_CAPTURE_UNSUPPORTED     = C.CUDA_ERROR_STREAM_CAPTURE_UNSUPPORTED
	CUDA_ERROR_STREAM_CAPTURE_INVALIDATED     = C.CUDA_ERROR_STREAM_CAPTURE_INVALIDATED
	CUDA_ERROR_STREAM_CAPTURE_MERGE           = C.CUDA_ERROR_STREAM_CAPTURE_MERGE
	CUDA_ERROR_STREAM_CAPTURE_UNMATCHED       = C.CUDA_ERROR_STREAM_CAPTURE_UNMATCHED
	CUDA_ERROR_STREAM_CAPTURE_UNJOINED        = C.CUDA_ERROR_STREAM_CAPTURE_UNJOINED
	CUDA_ERROR_STREAM_CAPTURE_ISOLATION       = C.CUDA_ERROR_STREAM_CAPTURE_ISOLATION
	CUDA_ERROR_STREAM_CAPTURE_IMPLICIT        = C.CUDA_ERROR_STREAM_CAPTURE_IMPLICIT
	CUDA_ERROR_CAPTURED_EVENT                 = C.CUDA_ERROR_CAPTURED_EVENT
	CUDA_ERROR_STREAM_CAPTURE_WRONG_THREAD    = C.CUDA_ERROR_STREAM_CAPTURE_WRONG_THREAD
	CUDA_ERROR_UNKNOWN                        = C.CUDA_ERROR_UNKNOWN
)

const (
	CU_DEVICE_ATTRIBUTE_MAX_THREADS_PER_BLOCK                        = C.CU_DEVICE_ATTRIBUTE_MAX_THREADS_PER_BLOCK
	CU_DEVICE_ATTRIBUTE_MAX_BLOCK_DIM_X                              = C.CU_DEVICE_ATTRIBUTE_MAX_BLOCK_DIM_X
	CU_DEVICE_ATTRIBUTE_MAX_BLOCK_DIM_Y                              = C.CU_DEVICE_ATTRIBUTE_MAX_BLOCK_DIM_Y
	CU_DEVICE_ATTRIBUTE_MAX_BLOCK_DIM_Z                              = C.CU_DEVICE_ATTRIBUTE_MAX_BLOCK_DIM_Z
	CU_DEVICE_ATTRIBUTE_MAX_GRID_DIM_X                               = C.CU_DEVICE_ATTRIBUTE_MAX_GRID_DIM_X
	CU_DEVICE_ATTRIBUTE_MAX_GRID_DIM_Y                               = C.CU_DEVICE_ATTRIBUTE_MAX_GRID_DIM_Y
	CU_DEVICE_ATTRIBUTE_MAX_GRID_DIM_Z                               = C.CU_DEVICE_ATTRIBUTE_MAX_GRID_DIM_Z
	CU_DEVICE_ATTRIBUTE_MAX_SHARED_MEMORY_PER_BLOCK                  = C.CU_DEVICE_ATTRIBUTE_MAX_SHARED_MEMORY_PER_BLOCK
	CU_DEVICE_ATTRIBUTE_SHARED_MEMORY_PER_BLOCK                      = C.CU_DEVICE_ATTRIBUTE_SHARED_MEMORY_PER_BLOCK
	CU_DEVICE_ATTRIBUTE_TOTAL_CONSTANT_MEMORY                        = C.CU_DEVICE_ATTRIBUTE_TOTAL_CONSTANT_MEMORY
	CU_DEVICE_ATTRIBUTE_WARP_SIZE                                    = C.CU_DEVICE_ATTRIBUTE_WARP_SIZE
	CU_DEVICE_ATTRIBUTE_MAX_PITCH                                    = C.CU_DEVICE_ATTRIBUTE_MAX_PITCH
	CU_DEVICE_ATTRIBUTE_MAX_REGISTERS_PER_BLOCK                      = C.CU_DEVICE_ATTRIBUTE_MAX_REGISTERS_PER_BLOCK
	CU_DEVICE_ATTRIBUTE_REGISTERS_PER_BLOCK                          = C.CU_DEVICE_ATTRIBUTE_REGISTERS_PER_BLOCK
	CU_DEVICE_ATTRIBUTE_CLOCK_RATE                                   = C.CU_DEVICE_ATTRIBUTE_CLOCK_RATE
	CU_DEVICE_ATTRIBUTE_TEXTURE_ALIGNMENT                            = C.CU_DEVICE_ATTRIBUTE_TEXTURE_ALIGNMENT
	CU_DEVICE_ATTRIBUTE_GPU_OVERLAP                                  = C.CU_DEVICE_ATTRIBUTE_GPU_OVERLAP
	CU_DEVICE_ATTRIBUTE_MULTIPROCESSOR_COUNT                         = C.CU_DEVICE_ATTRIBUTE_MULTIPROCESSOR_COUNT
	CU_DEVICE_ATTRIBUTE_KERNEL_EXEC_TIMEOUT                          = C.CU_DEVICE_ATTRIBUTE_KERNEL_EXEC_TIMEOUT
	CU_DEVICE_ATTRIBUTE_INTEGRATED                                   = C.CU_DEVICE_ATTRIBUTE_INTEGRATED
	CU_DEVICE_ATTRIBUTE_CAN_MAP_HOST_MEMORY                          = C.CU_DEVICE_ATTRIBUTE_CAN_MAP_HOST_MEMORY
	CU_DEVICE_ATTRIBUTE_COMPUTE_MODE                                 = C.CU_DEVICE_ATTRIBUTE_COMPUTE_MODE
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE1D_WIDTH                      = C.CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE1D_WIDTH
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_WIDTH                      = C.CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_WIDTH
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_HEIGHT                     = C.CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_HEIGHT
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE3D_WIDTH                      = C.CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE3D_WIDTH
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE3D_HEIGHT                     = C.CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE3D_HEIGHT
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE3D_DEPTH                      = C.CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE3D_DEPTH
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_LAYERED_WIDTH              = C.CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_LAYERED_WIDTH
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_LAYERED_HEIGHT             = C.CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_LAYERED_HEIGHT
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_LAYERED_LAYERS             = C.CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_LAYERED_LAYERS
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_ARRAY_WIDTH                = C.CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_ARRAY_WIDTH
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_ARRAY_HEIGHT               = C.CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_ARRAY_HEIGHT
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_ARRAY_NUMSLICES            = C.CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_ARRAY_NUMSLICES
	CU_DEVICE_ATTRIBUTE_SURFACE_ALIGNMENT                            = C.CU_DEVICE_ATTRIBUTE_SURFACE_ALIGNMENT
	CU_DEVICE_ATTRIBUTE_CONCURRENT_KERNELS                           = C.CU_DEVICE_ATTRIBUTE_CONCURRENT_KERNELS
	CU_DEVICE_ATTRIBUTE_ECC_ENABLED                                  = C.CU_DEVICE_ATTRIBUTE_ECC_ENABLED
	CU_DEVICE_ATTRIBUTE_PCI_BUS_ID                                   = C.CU_DEVICE_ATTRIBUTE_PCI_BUS_ID
	CU_DEVICE_ATTRIBUTE_PCI_DEVICE_ID                                = C.CU_DEVICE_ATTRIBUTE_PCI_DEVICE_ID
	CU_DEVICE_ATTRIBUTE_TCC_DRIVER                                   = C.CU_DEVICE_ATTRIBUTE_TCC_DRIVER
	CU_DEVICE_ATTRIBUTE_MEMORY_CLOCK_RATE                            = C.CU_DEVICE_ATTRIBUTE_MEMORY_CLOCK_RATE
	CU_DEVICE_ATTRIBUTE_GLOBAL_MEMORY_BUS_WIDTH                      = C.CU_DEVICE_ATTRIBUTE_GLOBAL_MEMORY_BUS_WIDTH
	CU_DEVICE_ATTRIBUTE_L2_CACHE_SIZE                                = C.CU_DEVICE_ATTRIBUTE_L2_CACHE_SIZE
	CU_DEVICE_ATTRIBUTE_MAX_THREADS_PER_MULTIPROCESSOR               = C.CU_DEVICE_ATTRIBUTE_MAX_THREADS_PER_MULTIPROCESSOR
	CU_DEVICE_ATTRIBUTE_ASYNC_ENGINE_COUNT                           = C.CU_DEVICE_ATTRIBUTE_ASYNC_ENGINE_COUNT
	CU_DEVICE_ATTRIBUTE_UNIFIED_ADDRESSING                           = C.CU_DEVICE_ATTRIBUTE_UNIFIED_ADDRESSING
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE1D_LAYERED_WIDTH              = C.CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE1D_LAYERED_WIDTH
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE1D_LAYERED_LAYERS             = C.CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE1D_LAYERED_LAYERS
	CU_DEVICE_ATTRIBUTE_CAN_TEX2D_GATHER                             = C.CU_DEVICE_ATTRIBUTE_CAN_TEX2D_GATHER
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_GATHER_WIDTH               = C.CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_GATHER_WIDTH
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_GATHER_HEIGHT              = C.CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_GATHER_HEIGHT
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE3D_WIDTH_ALTERNATE            = C.CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE3D_WIDTH_ALTERNATE
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE3D_HEIGHT_ALTERNATE           = C.CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE3D_HEIGHT_ALTERNATE
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE3D_DEPTH_ALTERNATE            = C.CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE3D_DEPTH_ALTERNATE
	CU_DEVICE_ATTRIBUTE_PCI_DOMAIN_ID                                = C.CU_DEVICE_ATTRIBUTE_PCI_DOMAIN_ID
	CU_DEVICE_ATTRIBUTE_TEXTURE_PITCH_ALIGNMENT                      = C.CU_DEVICE_ATTRIBUTE_TEXTURE_PITCH_ALIGNMENT
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURECUBEMAP_WIDTH                 = C.CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURECUBEMAP_WIDTH
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURECUBEMAP_LAYERED_WIDTH         = C.CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURECUBEMAP_LAYERED_WIDTH
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURECUBEMAP_LAYERED_LAYERS        = C.CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURECUBEMAP_LAYERED_LAYERS
	CU_DEVICE_ATTRIBUTE_MAXIMUM_SURFACE1D_WIDTH                      = C.CU_DEVICE_ATTRIBUTE_MAXIMUM_SURFACE1D_WIDTH
	CU_DEVICE_ATTRIBUTE_MAXIMUM_SURFACE2D_WIDTH                      = C.CU_DEVICE_ATTRIBUTE_MAXIMUM_SURFACE2D_WIDTH
	CU_DEVICE_ATTRIBUTE_MAXIMUM_SURFACE2D_HEIGHT                     = C.CU_DEVICE_ATTRIBUTE_MAXIMUM_SURFACE2D_HEIGHT
	CU_DEVICE_ATTRIBUTE_MAXIMUM_SURFACE3D_WIDTH                      = C.CU_DEVICE_ATTRIBUTE_MAXIMUM_SURFACE3D_WIDTH
	CU_DEVICE_ATTRIBUTE_MAXIMUM_SURFACE3D_HEIGHT                     = C.CU_DEVICE_ATTRIBUTE_MAXIMUM_SURFACE3D_HEIGHT
	CU_DEVICE_ATTRIBUTE_MAXIMUM_SURFACE3D_DEPTH                      = C.CU_DEVICE_ATTRIBUTE_MAXIMUM_SURFACE3D_DEPTH
	CU_DEVICE_ATTRIBUTE_MAXIMUM_SURFACE1D_LAYERED_WIDTH              = C.CU_DEVICE_ATTRIBUTE_MAXIMUM_SURFACE1D_LAYERED_WIDTH
	CU_DEVICE_ATTRIBUTE_MAXIMUM_SURFACE1D_LAYERED_LAYERS             = C.CU_DEVICE_ATTRIBUTE_MAXIMUM_SURFACE1D_LAYERED_LAYERS
	CU_DEVICE_ATTRIBUTE_MAXIMUM_SURFACE2D_LAYERED_WIDTH              = C.CU_DEVICE_ATTRIBUTE_MAXIMUM_SURFACE2D_LAYERED_WIDTH
	CU_DEVICE_ATTRIBUTE_MAXIMUM_SURFACE2D_LAYERED_HEIGHT             = C.CU_DEVICE_ATTRIBUTE_MAXIMUM_SURFACE2D_LAYERED_HEIGHT
	CU_DEVICE_ATTRIBUTE_MAXIMUM_SURFACE2D_LAYERED_LAYERS             = C.CU_DEVICE_ATTRIBUTE_MAXIMUM_SURFACE2D_LAYERED_LAYERS
	CU_DEVICE_ATTRIBUTE_MAXIMUM_SURFACECUBEMAP_WIDTH                 = C.CU_DEVICE_ATTRIBUTE_MAXIMUM_SURFACECUBEMAP_WIDTH
	CU_DEVICE_ATTRIBUTE_MAXIMUM_SURFACECUBEMAP_LAYERED_WIDTH         = C.CU_DEVICE_ATTRIBUTE_MAXIMUM_SURFACECUBEMAP_LAYERED_WIDTH
	CU_DEVICE_ATTRIBUTE_MAXIMUM_SURFACECUBEMAP_LAYERED_LAYERS        = C.CU_DEVICE_ATTRIBUTE_MAXIMUM_SURFACECUBEMAP_LAYERED_LAYERS
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE1D_LINEAR_WIDTH               = C.CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE1D_LINEAR_WIDTH
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_LINEAR_WIDTH               = C.CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_LINEAR_WIDTH
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_LINEAR_HEIGHT              = C.CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_LINEAR_HEIGHT
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_LINEAR_PITCH               = C.CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_LINEAR_PITCH
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_MIPMAPPED_WIDTH            = C.CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_MIPMAPPED_WIDTH
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_MIPMAPPED_HEIGHT           = C.CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_MIPMAPPED_HEIGHT
	CU_DEVICE_ATTRIBUTE_COMPUTE_CAPABILITY_MAJOR                     = C.CU_DEVICE_ATTRIBUTE_COMPUTE_CAPABILITY_MAJOR
	CU_DEVICE_ATTRIBUTE_COMPUTE_CAPABILITY_MINOR                     = C.CU_DEVICE_ATTRIBUTE_COMPUTE_CAPABILITY_MINOR
	CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE1D_MIPMAPPED_WIDTH            = C.CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE1D_MIPMAPPED_WIDTH
	CU_DEVICE_ATTRIBUTE_STREAM_PRIORITIES_SUPPORTED                  = C.CU_DEVICE_ATTRIBUTE_STREAM_PRIORITIES_SUPPORTED
	CU_DEVICE_ATTRIBUTE_GLOBAL_L1_CACHE_SUPPORTED                    = C.CU_DEVICE_ATTRIBUTE_GLOBAL_L1_CACHE_SUPPORTED
	CU_DEVICE_ATTRIBUTE_LOCAL_L1_CACHE_SUPPORTED                     = C.CU_DEVICE_ATTRIBUTE_LOCAL_L1_CACHE_SUPPORTED
	CU_DEVICE_ATTRIBUTE_MAX_SHARED_MEMORY_PER_MULTIPROCESSOR         = C.CU_DEVICE_ATTRIBUTE_MAX_SHARED_MEMORY_PER_MULTIPROCESSOR
	CU_DEVICE_ATTRIBUTE_MAX_REGISTERS_PER_MULTIPROCESSOR             = C.CU_DEVICE_ATTRIBUTE_MAX_REGISTERS_PER_MULTIPROCESSOR
	CU_DEVICE_ATTRIBUTE_MANAGED_MEMORY                               = C.CU_DEVICE_ATTRIBUTE_MANAGED_MEMORY
	CU_DEVICE_ATTRIBUTE_MULTI_GPU_BOARD                              = C.CU_DEVICE_ATTRIBUTE_MULTI_GPU_BOARD
	CU_DEVICE_ATTRIBUTE_MULTI_GPU_BOARD_GROUP_ID                     = C.CU_DEVICE_ATTRIBUTE_MULTI_GPU_BOARD_GROUP_ID
	CU_DEVICE_ATTRIBUTE_HOST_NATIVE_ATOMIC_SUPPORTED                 = C.CU_DEVICE_ATTRIBUTE_HOST_NATIVE_ATOMIC_SUPPORTED
	CU_DEVICE_ATTRIBUTE_SINGLE_TO_DOUBLE_PRECISION_PERF_RATIO        = C.CU_DEVICE_ATTRIBUTE_SINGLE_TO_DOUBLE_PRECISION_PERF_RATIO
	CU_DEVICE_ATTRIBUTE_PAGEABLE_MEMORY_ACCESS                       = C.CU_DEVICE_ATTRIBUTE_PAGEABLE_MEMORY_ACCESS
	CU_DEVICE_ATTRIBUTE_CONCURRENT_MANAGED_ACCESS                    = C.CU_DEVICE_ATTRIBUTE_CONCURRENT_MANAGED_ACCESS
	CU_DEVICE_ATTRIBUTE_COMPUTE_PREEMPTION_SUPPORTED                 = C.CU_DEVICE_ATTRIBUTE_COMPUTE_PREEMPTION_SUPPORTED
	CU_DEVICE_ATTRIBUTE_CAN_USE_HOST_POINTER_FOR_REGISTERED_MEM      = C.CU_DEVICE_ATTRIBUTE_CAN_USE_HOST_POINTER_FOR_REGISTERED_MEM
	CU_DEVICE_ATTRIBUTE_CAN_USE_STREAM_MEM_OPS                       = C.CU_DEVICE_ATTRIBUTE_CAN_USE_STREAM_MEM_OPS
	CU_DEVICE_ATTRIBUTE_CAN_USE_64_BIT_STREAM_MEM_OPS                = C.CU_DEVICE_ATTRIBUTE_CAN_USE_64_BIT_STREAM_MEM_OPS
	CU_DEVICE_ATTRIBUTE_CAN_USE_STREAM_WAIT_VALUE_NOR                = C.CU_DEVICE_ATTRIBUTE_CAN_USE_STREAM_WAIT_VALUE_NOR
	CU_DEVICE_ATTRIBUTE_COOPERATIVE_LAUNCH                           = C.CU_DEVICE_ATTRIBUTE_COOPERATIVE_LAUNCH
	CU_DEVICE_ATTRIBUTE_COOPERATIVE_MULTI_DEVICE_LAUNCH              = C.CU_DEVICE_ATTRIBUTE_COOPERATIVE_MULTI_DEVICE_LAUNCH
	CU_DEVICE_ATTRIBUTE_MAX_SHARED_MEMORY_PER_BLOCK_OPTIN            = C.CU_DEVICE_ATTRIBUTE_MAX_SHARED_MEMORY_PER_BLOCK_OPTIN
	CU_DEVICE_ATTRIBUTE_CAN_FLUSH_REMOTE_WRITES                      = C.CU_DEVICE_ATTRIBUTE_CAN_FLUSH_REMOTE_WRITES
	CU_DEVICE_ATTRIBUTE_HOST_REGISTER_SUPPORTED                      = C.CU_DEVICE_ATTRIBUTE_HOST_REGISTER_SUPPORTED
	CU_DEVICE_ATTRIBUTE_PAGEABLE_MEMORY_ACCESS_USES_HOST_PAGE_TABLES = C.CU_DEVICE_ATTRIBUTE_PAGEABLE_MEMORY_ACCESS_USES_HOST_PAGE_TABLES
	CU_DEVICE_ATTRIBUTE_DIRECT_MANAGED_MEM_ACCESS_FROM_HOST          = C.CU_DEVICE_ATTRIBUTE_DIRECT_MANAGED_MEM_ACCESS_FROM_HOST
	CU_DEVICE_ATTRIBUTE_MAX                                          = C.CU_DEVICE_ATTRIBUTE_MAX
)

const (
	CU_STREAM_DEFAULT      = C.CU_STREAM_DEFAULT
	CU_STREAM_NON_BLOCKING = C.CU_STREAM_NON_BLOCKING
)
